### ISSUE TITLE
Imports on CPU-only machine fail

### ISSUE THREAD

**Issue by Tomiinek** [DeMoriarty/TorchPQ#18]
Hello, 

I am trying to run your awesome CUDA-powered k-means. For testing purposes, I would like to make it runnable also on CPU, but I am getting errors during importing because of this: https://github.com/DeMoriarty/TorchPQ/blob/b8bbadf7915b8fead9a1b0f2dafa964b4058f26d/torchpq/kernels/default_device.py#L3

which results in:
```
CUDARuntimeError: cudaErrorNoDevice: no CUDA-capable device is detected
```

Would you mind changing it to something like:
``` python
if torch.cuda.is_available():
  __device = cp.cuda.Device().id
else:
  __device = None
```
or hiding the imports of `get_default_device` and `set_default_device` (they seem to be imported after checking `torch.cuda.is_available()` anyway, so it should be possible)?

And also getting rid / hiding this:
https://github.com/DeMoriarty/TorchPQ/blob/b8bbadf7915b8fead9a1b0f2dafa964b4058f26d/torchpq/__init__.py#L22

**Comment by DeMoriarty** [comment]
Hi, thanks for trying TorchPQ out!

Unfortunately, currently there's no cpu version of kmeans, since major parts of the code is written in cuda. The changes you suggested could make it possible to *import* TorchPQ in cpu only environment, but you will not be able to run any of the modules.

You can take a look at [fast-pytorch-kmeans](https://github.com/DeMoriarty/fast_pytorch_kmeans), it's implemented purely in python & pytorch, you can run it on both cpu and cuda, and it's pretty fast. The only issue you might face is out-of-memory errors when your dataset or the number of desired clusters is large.

**Comment by Tomiinek** [comment]
Thank you for you prompt reply :slightly_smiling_face: 

> Unfortunately, currently there's no cpu version of kmeans, since major parts of the code is written in cuda. 

Yeah that is exatcly what I had in mind :smile: But I probably changed my mind, the current version is fine.

> You can take a look at [fast-pytorch-kmeans](https://github.com/DeMoriarty/fast_pytorch_kmeans), it's implemented purely in python & pytorch, you can run it on both cpu and cuda, and it's pretty fast. The only issue you might face is out-of-memory errors when your dataset or the number of desired clusters is large.

You made my day, thanks :+1:
